<a href="https://colab.research.google.com/github/TheDarkExecutive/MachineLearningArc/blob/main/fake_news_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem.porter import  PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [3]:
print(stopwords.words)

<bound method WordListCorpusReader.words of <WordListCorpusReader in '/root/nltk_data/corpora/stopwords'>>

printing the stopwords (unnecessary words from the articles)

In [7]:
print(stopwords.words('english'))

['a', 'about', 'above', 'after', 'again', 'against', 'ain', 'all', 'am', 'an', 'and', 'any', 'are', 'aren', "aren't", 'as', 'at', 'be', 'because', 'been', 'before', 'being', 'below', 'between', 'both', 'but', 'by', 'can', 'couldn', "couldn't", 'd', 'did', 'didn', "didn't", 'do', 'does', 'doesn', "doesn't", 'doing', 'don', "don't", 'down', 'during', 'each', 'few', 'for', 'from', 'further', 'had', 'hadn', "hadn't", 'has', 'hasn', "hasn't", 'have', 'haven', "haven't", 'having', 'he', "he'd", "he'll", 'her', 'here', 'hers', 'herself', "he's", 'him', 'himself', 'his', 'how', 'i', "i'd", 'if', "i'll", "i'm", 'in', 'into', 'is', 'isn', "isn't", 'it', "it'd", "it'll", "it's", 'its', 'itself', "i've", 'just', 'll', 'm', 'ma', 'me', 'mightn', "mightn't", 'more', 'most', 'mustn', "mustn't", 'my', 'myself', 'needn', "needn't", 'no', 'nor', 'not', 'now', 'o', 'of', 'off', 'on', 'once', 'only', 'or', 'other', 'our', 'ours', 'ourselves', 'out', 'over', 'own', 're', 's', 'same', 'shan', "shan't", 'she', "she'd", "she'll", "she's", 'should', 'shouldn', "shouldn't", "should've", 'so', 'some', 'such', 't', 'than', 'that', "that'll", 'the', 'their', 'theirs', 'them', 'themselves', 'then', 'there', 'these', 'they', "they'd", "they'll", "they're", "they've", 'this', 'those', 'through', 'to', 'too', 'under', 'until', 'up', 've', 'very', 'was', 'wasn', "wasn't", 'we', "we'd", "we'll", "we're", 'were', 'weren', "weren't", "we've", 'what', 'when', 'where', 'which', 'while', 'who', 'whom', 'why', 'will', 'with', 'won', "won't", 'wouldn', "wouldn't", 'y', 'you', "you'd", "you'll", 'your', "you're", 'yours', 'yourself', 'yourselves', "you've"]

Pre-processing the data

In [8]:
news_dataset = pd.read_csv('/content/fakedata.csv')

In [10]:
news_dataset.shape

(44879, 3)

In [12]:
news_dataset.head()

                                               title   subject  Check
0  Putin tells Maduro: we'll keep cooperating wit...     world      1
1  Britain's Johnson: We will stress importance o...  politics      1
2   Lifetime Texas Republican Leaves The GOP In E...      News      0
3  Russian foreign minister: Trump team are peopl...  politics      1
4   Vicious Trump Fans Send BLOODCURDLING Threats...      News      0

counting missing values in dataset

In [13]:
news_dataset.isnull().sum()

title      0
subject    0
Check      0
dtype: int64

to replace null values with empty strings (to prevent dropping)
<br>
news_dataset = news_dataset.fillna('')

Using title and subject column under one umbrella to predict better

In [16]:
news_dataset['content'] = news_dataset['title'] +' '+ news_dataset['subject']

In [19]:
news_dataset.head()

                                               title  ...                                            content
0  Putin tells Maduro: we'll keep cooperating wit...  ...  Putin tells Maduro: we'll keep cooperating wit...
1  Britain's Johnson: We will stress importance o...  ...  Britain's Johnson: We will stress importance o...
2   Lifetime Texas Republican Leaves The GOP In E...  ...   Lifetime Texas Republican Leaves The GOP In E...
3  Russian foreign minister: Trump team are peopl...  ...  Russian foreign minister: Trump team are peopl...
4   Vicious Trump Fans Send BLOODCURDLING Threats...  ...   Vicious Trump Fans Send BLOODCURDLING Threats...

[5 rows x 4 columns]